# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the producer script into the container
COPY producer.py .

# Install kafka-python
RUN pip install kafka-python

# Run producer.py when the container launches
CMD ["python", "-u", "producer.py"]
