# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the processor API script into the container
COPY processor_api.py .

# Install dependencies
RUN pip install Flask kafka-python gunicorn Flask-Cors

# Expose the port the app runs on
EXPOSE 5001

# Command to run the application using Gunicorn
CMD ["gunicorn", "--bind", "0.0.0.0:5001", "--workers", "1", "processor_api:app"]
